# Generated by Django 3.0.7 on 2020-06-18 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20200618_2037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favorite',
            name='url',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='favorite',
            name='urlToImage',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
